describe('Activity Form', () => {
  it('should fetch 2 rows', () => {
    cy.request('POST', 'http://localhost:1938/api/MyActivity/list').as('getActivities')
    cy.get('@getActivities').then(res => {
      expect(res.body.length).equal(2)
    })
  })
  it('should display the form', () => {
    cy.visit('/')
    cy.contains('Thanks for Sharing Post').should('exist')
    cy.contains('Thanks for Sharing Liked').should('exist')
  })
  it('should open the modal', () => {
    cy.get('[data-cy="create-activity"]').click()
    cy.get('[data-cy="input-descr"]').should('exist')
  })
  it('should show errors on clicking Confirm', () => {
    cy.get('[data-cy="modal-confirm"]').click()
    cy.contains('Please input activity description').should('exist')
    cy.contains('Please select social platform').should('exist')
    cy.contains('Please select social type').should('exist')
  })
  it('should validate description', () => {
    cy.get('[data-cy="input-descr"]').type('aa')
    cy.get('[data-cy="modal-confirm"]').click()
    cy.contains('Length should be at least 3').should('exist')
    cy.get('[data-cy="input-descr"]').clear().type('test activity')
    cy.get('[data-cy="modal-confirm"]').click()
    cy.contains('Length should be at least 3').should('not.exist')
  })
  it('should select platform and type', () => {
    cy.get('[data-cy="select-platform"]').click()
    cy.contains('Facebook').click()
    cy.get('[data-cy="select-type"]').click()
    cy.get('[data-cy="option-liked"]').click()
  })
  it('should enter points and click confirm', () => {
    cy.get('[data-cy="input-points"]').clear().type('765')
    cy.get('[data-cy="modal-confirm"]').click()
    cy.wait(100)
    cy.get('[data-cy="input-descr"]').should('not.exist')
    cy.contains('Thanks for test activity').should('exist')
  })
  it('should modify data ', () => {
    cy.get('[data-cy="edit-test activity"]').click()
    cy.get('[data-cy="input-descr"]').clear().type('test description')
    cy.get('[data-cy="select-platform"]').click()
    cy.contains('Twitter').click()
    cy.get('[data-cy="select-type"]').click()
    cy.get('[data-cy="option-shared"]').click()
    cy.get('[data-cy="modal-confirm"]').click()
    cy.get('[data-cy="edit-test-activity"]').should('not.exist')
    cy.get('[data-cy="edit-test-description"]').should('not.exist')
    cy.contains('Thanks for test description').should('exist')
  })
  it('should delete ', () => {
    cy.get('[data-cy="delete-test description"]').click()
    cy.contains('Are you sure you want to delete this Activity?').should('exist')
    cy.get('[data-cy="confirm-no"]').click()
    cy.contains('Are you sure you want to delete this Activity?').should('not.exist')
    cy.get('[data-cy="delete-test description"]').click()
    cy.get('[data-cy="confirm-yes"]').click()
    cy.get('[data-cy="delete-test description"]').should('not.exist')
  })
})